
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS GUESTS;
DROP TABLE IF EXISTS BOOKING;

CREATE SEQUENCE IF NOT EXISTS ROOM_SEQ;
CREATE SEQUENCE IF NOT EXISTS GUESTS_SEQ;
CREATE SEQUENCE IF NOT EXISTS BOOKING_SEQ;


CREATE TABLE ROOM(
  ROOM_ID BIGINT DEFAULT ROOM_SEQ.nextval,
  NAME VARCHAR(16) NOT NULL,
  ROOM_NUMBER CHAR(2) NOT NULL UNIQUE,
  BED_INFO CHAR(2) NOT NULL,
  PRIMARY KEY (ROOM_ID)
);

CREATE TABLE GUEST(
  GUEST_ID BIGINT DEFAULT GUESTS_SEQ.nextval,
  GUEST_CODE VARCHAR(20),
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(64),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24),
  PRIMARY KEY (GUEST_CODE)
);

CREATE TABLE BOOKING(
  RESERVATION_ID BIGINT DEFAULT BOOKING_SEQ.nextval,
  ROOM_ID BIGINT NOT NULL,
  GUEST_CODE BIGINT NOT NULL,
  RES_DATE DATE,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM,
  FOREIGN KEY (GUEST_CODE) REFERENCES GUEST

);

CREATE INDEX IDX_RES_DATE ON BOOKING (RES_DATE);